Based on the images provided, here are all the questions from the eNova Software and Hardware Solutions Pvt. Ltd. Assessment - 3.

PHP Core / Debugging (30 marks)
The following object-oriented PHP code has multiple issues, causing it to either break or produce incorrect results. Identify and fix the errors. (Includes Product and Cart classes).

For security reasons, a payment platform wants to display only the last four digits of a credit card number and mask the rest with asterisks. Write a PHP function that takes a credit card number as a string and returns it in a masked format (e.g., "************5678").

A client has a requirement to remove all special characters from user input strings before saving them in the database. Write a PHP function that takes a string and removes all non-alphanumeric characters (except spaces).

Write a PHP script that reverses an array of numbers using a while loop.

Create a PHP form that collects a user's name, email, phone number, DOB, and password. Implement form validation to ensure:

The name field is not empty.

The email field contains a valid email address.

The password is at least 8 characters long.

The phone number contains exactly 10 digits.

The date of birth is in the format YYYY-MM-DD and is a valid date.

Display error messages for any invalid input.

Advanced MCQ with explanation (10 marks)
What is the output? Explain in 2 lines. (Code snippet involving a Test class with __construct and __toString).

Given the following CodeIgniter controller method, what is the primary purpose of using $this->load->model()? Explain in 1 line.

What is the output of the following PHP code snippet? (Code snippet involving reference variables &$foo).

What will be the output of the following PHP code snippet involving array_merge()?

Code Efficiency (10 marks)
Write a PHP function to sort a multidimensional array based on a specific key.

Write a PHP function that finds common elements present in all provided arrays.

Logical thinking - Array & string (mark 10)
Reversing a Subset of an Array: Given an array of integers, write a PHP function to reverse the elements between two given indices without affecting the rest of the array.

Write a PHP function to remove all duplicate elements from an array without using built-in array functions.

Write a PHP function to find the smallest subarray (contiguous) in an array that has a sum greater than or equal to a given number.

Write a PHP function to check the strength of a password based on certain rules: it must be at least 8 characters long, contain at least one uppercase letter, one lowercase letter, one digit, and one special character.

Write a PHP function that sorts an array of associative arrays by a nested key (e.g., sorting by 'age' inside an 'info' key).

SQL task - 30 mark
Write an SQL query to get the top 5 highest salaries from the employees table, sorted in descending order.

Write an SQL query to join two tables, employees and departments, where employees has a column department_id and departments has a column id. Select the employee names and their department names.

Write an SQL query to find the average salary of employees in each department from the employees table, grouped by department.

Find the total number of orders placed by each customer. (Based on the provided Schema).

Calculate the average order value for each product category.

Determine the top 5 best-selling products based on total quantity sold.

List all customers and their orders, including order details and product information.

Find the total revenue generated by each product category.

Sort the list of customers by last name in ascending order.

Sort the list of orders by order date in descending order.

Create a new table named reviews to store customer reviews for products.

Add a new column named discount to the orders table.

Drop the categories table.



Here are the additional questions found in the new image from the eNova Software and Hardware Solutions Pvt. Ltd. Assessment - 3.

SQL Questions
These questions relate to the student and course tables shown in your previous images:

Find the students who have enrolled in the course "Mathematics".

List all the courses taken by the student with student_id = 1.

Calculate the average grade of all students in the 10th class.

Find the students who have obtained a grade of 'A+' in any course.

Determine the total number of students enrolled in each department.

Reading Comprehension (10 marks)
The assessment includes a passage regarding an online marketplace platform. Based on the text, the key features of the platform include:

Product Catalog: A meticulously organized catalog with detailed descriptions, high-resolution images, and competitive pricing.

Personalized Accounts: Empowering customers with accounts to track orders, save favorites, and receive tailored recommendations.

Intuitive Shopping Cart: A seamless experience for adding, removing, and managing selected items.

Secure Transactions: Ensuring customer confidence with secure payment options like credit cards and digital wallets.

Real-time Updates: Keeping customers informed with real-time order tracking and delivery notifications.

Comprehensive Support: Offering efficient support channels including email, chat, and phone.

Community-Driven Feedback: Fostering community by allowing customers to rate and review products.

Intelligent Recommendations: Leveraging algorithms to suggest products aligned with customer preferences and purchase history.

Mobile-First Approach: Prioritizing a responsive experience across all devices, ensuring the platform is accessible on mobile.

Search Engine Optimization: Enhancing online visibility to attract more customers.
